name: One-time Prisma DB Push
on:
  workflow_dispatch: {}

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安全に接続先だけログ（パス等は出さない）
      - name: Show target (masked)
        run: |
          node -e "
            const u = new URL(process.env.DATABASE_URL);
            console.log('Host:', u.hostname);
            console.log('DB  :', u.pathname.slice(1));
            console.log('SSL :', u.searchParams.get('sslmode') || 'none');
            console.log('Pooler?', u.hostname.includes('-pooler'));
          "
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Neon がスリープ中などで失敗したら数秒待って再試行
      - name: Prisma DB Push (no install, retry)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          for i in 1 2 3; do
            npx -y prisma@5.22.0 db push --skip-generate --accept-data-loss && exit 0
            echo "Retry in 5s... ($i)"
            sleep 5
          done
          exit 1
