name: One-time Prisma DB Push

on:
  workflow_dispatch: {}   # 手動実行

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 依存インストールなし。npx で Prisma CLI を都度取得して実行
      - name: Prisma DB Push (no install)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx -y prisma@5.22.0 db push --skip-generate --accept-data-loss
